### PR TITLE
fix(message_input): Make mention list work in DMs

### LINKED ISSUE #637: Can't ping people on dm's
When i do the @ and put a single letter everithing crashes

### PR DESCRIPTION
**Pull request by xqrs**
Before this, typeing `@` in DMs hanged the entire client.
This patch fixes that and implements proper handling of DMs (DM and GroupDMs)

Edit:
Fixes #637

### CODE REVIEW

File: cmd/guilds_tree.go [hunk 1]
```diff
@@ -142,8 +142,6 @@ PARENT_CHANNELS:
 }
 
 func (gt *guildsTree) onSelected(node *tview.TreeNode) {
-	app.chatView.messageInput.reset()
```
Comment (ossenthusiast) [inline cmd/guilds_tree.go:145]: Is this supposed to not happen at all? I think the message input should be reset when a new channel is selected. So ig move this to in `case discord.ChannelID` branch?

File: cmd/guilds_tree.go [hunk 2]
```diff
@@ -183,6 +181,9 @@ func (gt *guildsTree) onSelected(node *tview.TreeNode) {
 			app.chatView.messagesList.requestGuildMembers(guildID, messages)
 		}
 
+		app.chatView.selectedChannel = channel
+		app.chatView.selectedGuildID = channel.GuildID
```
Comment (ossenthusiast) [inline cmd/guilds_tree.go]: We can probably get rid of selectedGuildID since `selectedChannel.GuildID` does the exact same thing.

File: cmd/guilds_tree.go (hunk 1 above)
Comment (xqrs) [reply cmd/guilds_tree.go:145]: `messageInput.reset()` (clear input box) should be called only when switching channels.

The user may actually be browsing other servers while chatting with someone.

File: cmd/guilds_tree.go [hunk 3]
```diff
@@ -197,9 +197,7 @@ func (gt *guildsTree) onSelected(node *tview.TreeNode) {
 			app.SetFocus(app.chatView.messageInput)
 		}
 
-		app.chatView.selectedChannelID = channel.ID
-		app.chatView.selectedGuildID = channel.GuildID
-	case nil: // Direct messages
+	case nil: // Direct messages folder
```
Comment (ayn2op) [inline cmd/guilds_tree.go:200]: unrelated change

Comment (ayn2op) [reply cmd/guilds_tree.go:200]: This does not make any sense, "Direct Messages" node is a `*tview.TreeNode`, not a folder.

Comment (xqrs) [reply cmd/guilds_tree.go:200]: When I was reading the code some late time of the night, I thought `case nil: // Direct messages` meant *DMs* as in it's selected when you choose one of the DMs channel. What should we actually call it? "Direct messages" is ambiguous between a list of channels and just one channel.
